
def get_training_data():
    TRAINING_DA = [
    ("John Doe works at OpenAI in San Francisco.", {"entities": [(0, 8, "PERSON"), (20, 26, "ORG"), (30, 43, "LOCATION")]}),
    ("Jane Smith is a researcher at Google.", {"entities": [(0, 10, "PERSON"), (29, 35, "ORG")]}),
    ("The hearing was conducted by Judge Anderson.", {"entities": [(30, 44, "JUDGE")]}),
    ("The new office is located in New York.", {"entities": [(25, 33, "LOCATION")]}),
    ("CEO Michael Johnson visited the Microsoft headquarters.", {"entities": [(4, 19, "PERSON"), (35, 44, "ORG")]}),
    ("Judge Thompson ruled in favor of the plaintiff.", {"entities": [(0, 14, "JUDGE")]}),
    ("Sara Lee is moving to Boston for her new role.", {"entities": [(0, 8, "PERSON"), (21, 27, "LOCATION")]}),
    ("Judge Williams presided over the court session.", {"entities": [(0, 14, "JUDGE")]}),
    ("Amazon has opened a new office in Seattle.", {"entities": [(0, 6, "ORG"), (31, 37, "LOCATION")]}),
    ("Mark Zuckerberg founded Facebook.", {"entities": [(0, 15, "PERSON"), (24, 32, "ORG")]}),
    ("Google is expanding its office in London.", {"entities": [(0, 6, "ORG"), (31, 37, "LOCATION")]}),
    ("Elon Musk, the CEO of Tesla, was in Berlin last week.", {"entities": [(0, 9, "PERSON"), (17, 22, "ORG"), (32, 38, "LOCATION")]}),
    ("Judge Roberts made the final decision.", {"entities": [(0, 13, "JUDGE")]}),
    ("The branch in Paris is among the largest.", {"entities": [(13, 18, "LOCATION")]}),
    ("The article was reviewed by Judge Harris.", {"entities": [(27, 39, "JUDGE")]}),
    ("Tesla has unveiled its new facility in Texas.", {"entities": [(0, 5, "ORG"), (35, 40, "LOCATION")]}),
    ("Anna Karenina is a famous book character.", {"entities": [(0, 13, "PERSON")]}),
    ("Judge Baker has over 20 years of experience.", {"entities": [(0, 11, "JUDGE")]}),
    ("Meta is building a new headquarters in Dublin.", {"entities": [(0, 4, "ORG"), (37, 43, "LOCATION")]}),
    ("The lawsuit was overseen by Judge Collins.", {"entities": [(26, 39, "JUDGE")]}),
    ("Nina Brown works for IBM.", {"entities": [(0, 10, "PERSON"), (20, 23, "ORG")]}),
    ("The London office will handle international cases.", {"entities": [(4, 10, "LOCATION")]}),
    ("Twitter appointed a new CEO.", {"entities": [(0, 7, "ORG")]}),
    ("Judge Matthews is presiding over this case.", {"entities": [(0, 14, "JUDGE")]}),
    ("Spotify is increasing its workforce in Stockholm.", {"entities": [(0, 7, "ORG"), (37, 45, "LOCATION")]}),
    ("Judge White wrote the official report.", {"entities": [(0, 11, "JUDGE")]}),
    ("The trial took place in Los Angeles.", {"entities": [(21, 32, "LOCATION")]}),
    ("Apple has announced new products this year.", {"entities": [(0, 5, "ORG")]}),
    ("Judge Carter was interviewed by the press.", {"entities": [(0, 12, "JUDGE")]}),
    ("They expanded the team in Toronto.", {"entities": [(25, 32, "LOCATION")]}),
    ("NASA launched a new satellite.", {"entities": [(0, 4, "ORG")]}),
    ("Judge Wilson ruled in favor of the defendant.", {"entities": [(0, 12, "JUDGE")]}),
    ("They relocated to Vancouver for the project.", {"entities": [(16, 25, "LOCATION")]}),
    ("The verdict was given by Judge Patel.", {"entities": [(25, 36, "JUDGE")]}),
    ("Microsoft has a new office in Tokyo.", {"entities": [(0, 9, "ORG"), (26, 31, "LOCATION")]}),
    ("Emma Green is now working at Oracle.", {"entities": [(0, 10, "PERSON"), (28, 34, "ORG")]}),
    ("They hired new employees in Miami.", {"entities": [(27, 32, "LOCATION")]}),
    ("Judge Lee issued a preliminary statement.", {"entities": [(0, 9, "JUDGE")]}),
    ("The New York branch is the largest.", {"entities": [(4, 12, "LOCATION")]}),
    ("The team in Berlin will manage new accounts.", {"entities": [(12, 18, "LOCATION")]}),
    ("Netflix has launched new features.", {"entities": [(0, 7, "ORG")]}),
    ("The conference was organized by Judge Bell.", {"entities": [(33, 43, "JUDGE")]}),
    ("Uber plans to expand in Mexico City.", {"entities": [(0, 4, "ORG"), (22, 32, "LOCATION")]}),
    ("Dropbox is hiring new engineers.", {"entities": [(0, 7, "ORG")]}),
    ("Judge Cruz postponed the hearing.", {"entities": [(0, 10, "JUDGE")]}),
    ("They are opening a new site in Sydney.", {"entities": [(30, 36, "LOCATION")]}),
    ("Samsung released its latest model.", {"entities": [(0, 7, "ORG")]}),
    ("The court case was closed by Judge Parker.", {"entities": [(27, 38, "JUDGE")]}),
    ("Google operates from several offices.", {"entities": [(0, 6, "ORG")]}),
    ("Judge Green handled the appeal.", {"entities": [(0, 11, "JUDGE")]}),
    ("They opened an office in Los Angeles.", {"entities": [(25, 36, "LOCATION")]}),
    ("Intel is developing new processors.", {"entities": [(0, 5, "ORG")]}),
    ("The decision was written by Judge Edwards.", {"entities": [(27, 40, "JUDGE")]})
]

    return TRAINING_DA